# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codity_app', '0007_auto_20160605_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='metric',
            new_name='metric_id',
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set([('metric_id', 'sign', 'action')]),
        ),
    ]
