# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codity_app', '0009_auto_20160605_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='metric',
            field=models.CharField(choices=[(b'CPU', b'CPU'), (b'RAM', b'RAM'), (b'HDD', b'HDD')], max_length=100),
        ),
    ]
