# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codity_app', '0010_auto_20160608_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='codity_app.Metric'),
        ),
    ]
